# Generated by Django 5.0.13 on 2026-06-10 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
        ('documents', '0003_chunk_unique_and_fts_index'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace_id', '-created_at'], name='documents_workspa_30679c_idx'),
        ),
    ]
