# Generated by Django 5.0.13 on 2026-06-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session_id', 'created_at'], name='chat_messag_session_597c4e_idx'),
        ),
    ]
